cls_params:
  boosting_type: gbdt
  device: cpu
  gpu_device_id: 0
  gpu_platform_id: 0
  learning_rate: 0.015732043600075817
  metric: multi_logloss
  n_estimators: 52
  num_class: 4
  num_leaves: 126
  objective: multiclass
  random_state: 42
  verbose: 0
reg_params:
  colsample_bytree: 0.8690215583827708
  device: cpu
  learning_rate: 0.020479562055984522
  n_estimators: 932
  num_leaves: 126
  random_state: 42